"""
Tipo NONE

O TIPO DE DADO NONE REPRESENTA O TIPO SEM TIPO, TAMBEM CONHECIDO COMO TIPO FAZIO, POREM, O PRIMEIRO TERMO É MAIS
APROPRIADO.

O TIPO NONE É SEMPRE ESPECIFICADO COM A PRIMEIRO LETRA MAIUSCULA, COMO NO EXEOMPLO
PODEMOS UTILIZAR O NONE QUANDO QUEREMOS CRIAR UMA VARIÁVEL E QUEREMOS INICIALIZA-LA COM U TIPO SEM TIPO, ANTES DE
RECEBERMOS UM VALOR FINAL.

TIPO NONE É SEMPRE CONSIDERADO FALSE
"""
numeros = None
print(numeros)
print(type(numeros))
